### ISSUE TITLE
What does this software do?

### ISSUE THREAD

**Issue by evelynmitchell** [systeminit/si#2605]
### What happened?

Expecting to understand the project.

### How can we reproduce this?

Read the landing page.

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Other (please specify)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I know the project is exciting to those involved, but from the outside it is not clear what problem it solves, for who, and what alternatives exist to solve similar problems.

**Comment by nickgerace** [comment]
Hi @evelynmitchell! Good question. The README does not contain a good description of the software at this time. I've added a little blurb and a link to one our of blog posts in #2612. However, I suspect that PR will just be a first pass at tackling this issue. Thanks for raising it!

**Comment by nickgerace** [comment]
Upon reflection and letting this sit, we can close this issue as there is sufficient information to learn about the software. Thanks again!
