### ISSUE TITLE
[BUG-24] Can't copy text from an qualification failure

### ISSUE THREAD

**Issue by Octogonapus** [systeminit/si#2606]
### What happened?

I am trying to copy the text from a qualification failure, but when I go to select it with my mouse cursor, the window showing the failure closes.

### How can we reproduce this?

1. Open a qualification failure using the diagram outline panel (not the bottom bar) (mine was `Docker Image Exists`)
2. Use your mouse to select the failure text
3. The window closes when you click

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

<sub>[BUG-24](https://linear.app/system-initiative/issue/BUG-24/cant-copy-text-from-an-qualification-failure)</sub>

**Comment by adamhjk** [comment]
Hi! We'll work on making it selectable from the outline panel - thanks!

In the meantime, if you open the qualification from the sub-panel at the bottom, you should be able to select it.

**Comment by Octogonapus** [comment]
I get the feeling this might be related to https://github.com/tailwindlabs/headlessui/issues/2535 but I've been trying the listed fixes for a while and I can't get it working. Leaving this to someone more knowledgeable...
