### ISSUE TITLE
[COM-30] si start AWS keys should be optional

### ISSUE THREAD

**Issue by NickLarsenNZ** [systeminit/si#2630]
### Is this issue related to an issue?.

I'm would rather not have to enter AWS keys during `si start`, since I already have an AWS profile setup (and often use `aws sso login` instead of copying around keys).

This felt different from normal interactions where the AWS SDK is used (where it honours AWS_PROFILE, or use the default profile, etc...).

### Describe the outcome you'd like from us

`si start` could perhaps:
1. Show if an AWS profile is being used `eg: if `AWS_PROFILE` is set).
2. Ask if it should use that, or the default profile, or if the user would like to enter in specific keys.

### Describe alternatives you've considered

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

<sub>[COM-30](https://linear.app/system-initiative/issue/COM-30/si-start-aws-keys-should-be-optional)</sub>

**Comment by NickLarsenNZ** [comment]
A similar thing could be done for dockerhub credentials, where I have already done docker login (I haven't gotten so far to see if I can use other registries).

**Comment by adamhjk** [comment]
Yeah - we'll look into what the right thing to do here is. Ultimately, we want these to be put into the product and stored, rather than put in and then passed to the containers.

**Comment by adamhjk** [comment]
We're currently working on the way secrets are put in to System Initiative - we posted a read through of the opportunity and story map we're working here: https://www.youtube.com/watch?v=345aFwpCvF4
