### ISSUE TITLE
AWS Ingress Actions functions are not found

### ISSUE THREAD

**Issue by Octogonapus** [systeminit/si#2652]
### What happened?

All three Actions Functions of the AWS Ingress Asset display a "Function not found" error when viewing them.

https://github.com/systeminit/si/assets/4064722/71a8c680-81c5-46cf-8cd9-3b94a859a6d0

### How can we reproduce this?

Open the AWS Ingress Asset in the Customize view, and then view any of the Asset Functions.

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stack72** [comment]
Hey @Octogonapus 

Unfortunately we are not able to reproduce this - is this continually reproducible for you?

Paul

**Comment by Octogonapus** [comment]
I can't reproduce this after updating to the latest release.

**Comment by stack72** [comment]
Thanks for letting me know
