### ISSUE TITLE
Syntax highlighting breaks when opening a function after viewing an asset schema

### ISSUE THREAD

**Issue by Octogonapus** [systeminit/si#2653]
### What happened?

Syntax highlighting can break if you open a function in a particular way, described below.

https://github.com/systeminit/si/assets/4064722/48ca78a2-a61d-4596-9e3a-bafef835bc1e

### How can we reproduce this?

1. View an asset schema
2. Click on the tab of an open function
3. Observe syntax highlighting has broken

Notably, this does not break:
1. View the tab of an open function
2. Click on the tab of another open function
3. Observe syntax highlighting has not broken

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stack72** [comment]
Closed via https://github.com/systeminit/si/pull/2697
