### ISSUE TITLE
[COM-27] [Feature Request] Asset export / import button

### ISSUE THREAD

**Issue by KairuDeibisu** [systeminit/si#2658]
### Is this issue related to an issue?.

Currently, to share assets with other users. We need to copy and paste which can be cumbersome and time-consuming for a large number of assets.

### Describe the outcome you'd like from us

I would like the ability to export a list of assets, and all attached functions as JSON.

I would be able to send the file to another person. They could import the JSON file.

Additionally, for unit testing, The maintainers of si could set up components to reproduce a bug, then export the JSON file. This JSON file could be used in later unit tests to prevent regression, additionally, members of the community can attach these exports to assist in reproducing bugs.

### Describe alternatives you've considered

Sharing a version of assets from a specific change set using a link to import them into other si accounts.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

<sub>[COM-27](https://linear.app/system-initiative/issue/COM-27/[feature-request]-asset-export-import-button)</sub>

**Comment by adamhjk** [comment]
We're absolutely building this into the product. It won't work quite this way (you'll be able to share the work directly as a module) but the gist is the same.
