### ISSUE TITLE
[COM-26] [Feature Request] localstack support

### ISSUE THREAD

**Issue by Wolfsrudel** [systeminit/si#2659]
### Is this issue related to an issue?.

I don't like to see an AWS account, in which costs can arise, as a development environment if I can also map the whole thing locally.
Basically, I want to be able to work locally - isolated - independently of AWS.

### Describe the outcome you'd like from us

In order to be able to map a completely local development environment - i.e. to be independent of an AWS account - the integration of [localstack](https://localstack.cloud/)  at API endpoints would be very helpful.

### Describe alternatives you've considered

I believe the alternative to localstack would be the AWS API itself.
Possibly a dry run based on a `terraform plan` without actually generating the resources.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

<sub>[COM-26](https://linear.app/system-initiative/issue/COM-26/[feature-request]-localstack-support)</sub>

**Comment by keeb** [comment]
Hey @Wolfsrudel, thanks for the request! 

 It looks like we have an initial implementation of this support added. See #2882 and let us know if you give it a try.
