### ISSUE TITLE
[Bug] Can't delete nested frames of the same type

### ISSUE THREAD

**Issue by KairuDeibisu** [systeminit/si#2661]
### What happened?

Accidentally put two frames of the same asset on top of each other. The result was I could not delete the child frame. 

### How can we reproduce this?

1. Drag the AWS region on to the canvas.
2. Drag another AWS region on to the canvas.
3. Try to delete the nested canvas.

### Operating system

Windows via WSL2

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NeilHanlon** [comment]
two (three, maybe four if we count qol) issues from my perspective:

1. some frames can't logically nest to themselves, so there should be a way to prevent nesting, e.g., an AWS region in an AWS region, as this just.. doesn't make sense

2. A few UI bugs which relate to frames and nesting thereof -- I need to re-run my tests and actually note the bugs and how to reproduce them, but the Canvas is very shaky with lots of frames, and doesn't well understand how to map the relationships.


I can confirm that the method of changing the inner frame to a Component, and then deleting it (usually) works, but I've found sometimes it is possible to corrupt the workspace doing this

**Comment by paulocsanz** [comment]
Hey folks, sorry for the delay tackling this. But it has been fixed on main!
