### ISSUE TITLE
RFE: Abandon Changeset

### ISSUE THREAD

**Issue by NeilHanlon** [systeminit/si#2668]
### Is this issue related to an issue?.

While developing, it will be useful to abandon changes which may be corrupt (😅) or otherwise need to be deleted/abandoned. For example, one might want to visualize two different options with a colleague and then abandon the one they decide not to use.

In a related manner, being able to visualize the tree of changes might be helpful, like `git tree`, e.g.--that is probably out of scope of this RFE though

### Describe the outcome you'd like from us

Implement an API call and related UI element to abandon a change (with confirmation)

### Describe alternatives you've considered

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adamhjk** [comment]
Absolutely makes sense that we need to support abandoning change sets. I think there is quite a bit to be done around change set management and review, but this feels like the right place to start.

**Comment by stack72** [comment]
I am going to close this out as I just implemented it - https://github.com/systeminit/si/pull/2997

If you want me to feature toggle it on for you to try then let me know @NeilHanlon :)
