### ISSUE TITLE
[COM-31] Allow changing of the workspace URL

### ISSUE THREAD

**Issue by stack72** [systeminit/si#2696]
### Is this issue related to an issue?.

Currently, when you create a workspace, System Initiative believes that the URL of the workspace is localhost:8080. This isn't always the case as you could be running System Initiative on a server that others within your org are using to try it

### Describe the outcome you'd like from us

Have a way to be able to change the URL associated with a workspace - this would then potentially allow the auth portal to not always be checking that localhost:8080 was alive before reporting that a workspace was healthy

### Describe alternatives you've considered

We updated the record in the database for my user workspace to have the new URL and the auth portal immediately updated so we know this works as expected when we can give it the correct URL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I was able to run System Initiative on an ec2 instance by binding the web containers to 0.0.0.0 and access the web UI via the public IP of the AWS instance. This allowed me to get to the auth portal but the auth portal never allowed me to get back to the ec2 instance IP as it was hard coded to localhost:8080

<sub>[COM-31](https://linear.app/system-initiative/issue/COM-31/allow-changing-of-the-workspace-url)</sub>

**Comment by theoephraim** [comment]
Should be able to get to it this week :) Open to collaborating if you are so inclined.

**Comment by stack72** [comment]
This is now out there and working as expected
