### ISSUE TITLE
Collection of minor issues of the SI installer

### ISSUE THREAD

**Issue by keeb** [systeminit/si#2700]
### What happened?

Now that `--web-host` flags are introduced, there's some subtle issues.

* Subsequent runs after containers have been created the first time do not respect the `--web-host flag`
* Using `--web-host` only affects the web. Does not affect SDF which is listening on all interfaces by default.

### How can we reproduce this?

Deploy SI using the installer without specifying `--web-host` and then run `si --web-host 0.0.0.0 start` and notice it does not change

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Other (please specify)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I will add any other minor nits as I find them.

**Comment by keeb** [comment]
If you try to `si delete` while the stack is running it does not call stop and then delete, resulting in this error

```[keeb@system-init-installer ~]$ si delete
System Initiative Launcher is in "local" mode


Launcher update found, please run `si update` to install it

Deleting container: local-jaeger-1 (f6b19193f10c5e3521934b23efb2dcfb40c43f38e256f78e2f1529054c55b91d)
Error:
   0: docker api: error 409 Conflict - You cannot remove a running container f6b19193f10c5e3521934b23efb2dcfb40c43f38e25
6f78e2f1529054c55b91d. Stop the container before attempting removal or force remove
   1: error 409 Conflict - You cannot remove a running container f6b19193f10c5e3521934b23efb2dcfb40c43f38e256f78e2f15290
54c55b91d. Stop the container before attempting removal or force remove

Location:
   bin/si/src/main.rs:112```

**Comment by keeb** [comment]
There's no indication as to when the service is actually available. 

For my system on a fresh install, I get auth errors (`Not found` - which doesn't mean anything to me really) when hitting the local SI homepage (`http://localhost:8080` equivalent) until ~9 minutes after I have started.

I believe this is all of the DB setup/migrations that happen on first start.

**Comment by stack72** [comment]
@keeb this is fantastic! I can get this fixed up :) thank you!!

**Comment by stack72** [comment]
The last issue to be tackled here is that when the cli args change for host ip and port, we need to stop and recreate the web container
