### ISSUE TITLE
[COM-35] Management of VPCs with System Initiative

### ISSUE THREAD

**Issue by stack72** [systeminit/si#2819]
We need to be able to build systems on top of VPCs rather than always relying on the default vpc. To do this, there are a number of core resources that we need to be able to build:

* [X] VPC
* [X] Subnet
* [X] Internet Gateway
* [X] RouteTable
* [X] Route
* [X] RouteTableAssociation (these will not be actual resources but will be the edges between the components RouteTable and Route)
* [X] NatGateway
* [X] Iam Role / Policy
* [X] Cloudwatch Log Group

Ideally we should be able to create a VPC that has 3 public and 3 private Subnets and is able to route the traffic for the private subnets through the natgateway to the internet

<sub>From [SyncLinear.com](https://synclinear.com) | [COM-35](https://linear.app/system-initiative/issue/COM-35/management-of-vpcs-with-system-initiative)</sub>

**Comment by NeilHanlon** [comment]
oooh. one step closer to transit gateways ;)

**Comment by stack72** [comment]
I will ✅ these off as I finish and test the modules and add them to our module-index
