### ISSUE TITLE
Creating a LogGroup succeeds even if the update action failed

### ISSUE THREAD

**Issue by Octogonapus** [systeminit/si#3022]
### What happened?

I created a Cloudwatch LogGroup without setting the retention field. The create action succeeded, but the update action failed (logs below). Everything in the SI UI was green.

It looks like the bug is in serializing an empty retention parameter, which was set to `0` instead of being omitted entirely.

```
Running CLI command: "aws 'logs' 'create-log-group' '--cli-input-json' '{ "logGroupName": "si-0963", "tags": { "Name": "si-0963" } }' '--region' 'us-east-1'"

Running CLI command: "aws 'logs' 'put-retention-policy' '--log-group-name' 'si-0963' '--retention-in-days' '0' '--region' 'us-east-1'"

An error occurred (InvalidParameterException) when calling the PutRetentionPolicy operation: Invalid retention value. Valid values are: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1096, 1827, 2192, 2557, 2922, 3288, 3653]

Output: { "protocol": "result", "status": "success", "executionId": "ayrtonsennajscommand", "health": "warning", "message": "Unable to update Cloudwatch Logs LogGroup, AWS CLI 2 exited with non zero code: 254" }
```
![image](https://github.com/systeminit/si/assets/4064722/57f073a5-ced2-4f86-9db3-14c06d5b32f5)

### How can we reproduce this?

Create a Cloudwatch LogGroup without setting the retention field.

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stack72** [comment]
Hah! I jsut fixed this :) You will be able to get this in a latest version of the asset!
