### ISSUE TITLE
Security group ID is malformed (empty)

### ISSUE THREAD

**Issue by Octogonapus** [systeminit/si#3042]
### What happened?

I created a security group and an ingress rule and connected them. The ingress rule had a failing qualification `Can create ingress` which failed with this error:
```
Qualification Failures:

    An error occurred (InvalidGroupId.Malformed) when calling the AuthorizeSecurityGroupIngress operation: The security-group ID '' is malformed

Raw Output:

Running CLI command: "aws 'ec2' 'authorize-security-group-ingress' '--region' 'us-east-2' '--dry-run' '--cli-input-json' '{ "GroupId": "", "IpPermissions": [ { "FromPort": 0, "ToPort": 0, "IpProtocol": "All", "IpRanges": [ { "CidrIp": "0.0.0.0/0" } ] } ], "TagSpecifications": [ { "ResourceType": "security-group-rule", "Tags": [ { "Key": "Name", "Value": "si-8632" } ] } ] }'"

An error occurred (InvalidGroupId.Malformed) when calling the AuthorizeSecurityGroupIngress operation: The security-group ID '' is malformed

Output: { "protocol": "result", "status": "success", "executionId": "tomcruise", "data": { "result": "failure", "message": "\nAn error occurred (InvalidGroupId.Malformed) when calling the AuthorizeSecurityGroupIngress operation: The security-group ID '' is malformed" }, "unset": false }
```

Notably, the group ID is empty. This matches what we can see in the GUI:
![image](https://github.com/systeminit/si/assets/4064722/1d33a5ff-a722-4356-8947-ffb971005a4e)

I do not expect the ID to be empty because I connected the security group to the ingress, which should set the group ID:
![image](https://github.com/systeminit/si/assets/4064722/5fbb7455-903f-437c-a1dc-cb4f6536813d)

In trying to reproduce this, I also found another scenario where the group ID appeared empty in the GUI but there were no failing qualifications:
![image](https://github.com/systeminit/si/assets/4064722/70c1d7d1-5ad6-459b-baf6-e51c3a78e18e)

### How can we reproduce this?

This is somewhat reproducible. My general steps are:
1. Create the region
2. Create a security group
3. Create an ingress
4. Connect the security group and the ingress
5. Fill out an `IpPermissions` entry in the ingress
6. Wait

I do not wait between any of these steps; i.e. I perform them as fast as SI allows me to. Maybe this is related to these bugs?

I tried deleting and re-creating the edge between the security group and the ingress; this did not change the group ID on the ingress in the GUI, and the qualification function was still failing. Notably, nothing appears to happen when I create an edge. I would expect to see the ingress start qualification again, but it looks like nothing happens (no progress spinner, etc.).

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Debug info for the group ID:
![image](https://github.com/systeminit/si/assets/4064722/fd0eedb2-a9d9-4e39-9736-861db562b5df)

**Comment by stack72** [comment]
Thanks for this @Octogonapus 

Looking into it now!

**Comment by Octogonapus** [comment]
This is actually user error on my part, thanks for helping @stack72
