### ISSUE TITLE
SDF migration error after updating SI

### ISSUE THREAD

**Issue by Octogonapus** [systeminit/si#3049]
### What happened?

I am not sure if this is a bug or expected, but I experienced an SDF error after updating SI (while it was running, if that matters).

### How can we reproduce this?

This is everything I ran: https://pastebin.com/pDNmERpS
This box is a VM dedicated to running SI, so there are no dev builds present that could mess with the data layer.
This is the first time I have updated SI on this box.

### Operating system

Linux

### Architecture

x86_64 / amd64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by britmyerss** [comment]
Thanks for submitting @Octogonapus and I'm sorry you ran into this!  Until now, we have been editing our migrations directly, but going forward we will authoring new migrations and ensuring we handle upgrades appropriately.  I'm going to close this issue as this is more of a procedural change we need to make!
