### ISSUE TITLE
Support to NixOS

### ISSUE THREAD

**Issue by selmison** [systeminit/si#3074]
### Is this issue related to an issue?.

SI does not work with NixOS.

### Describe the outcome you'd like from us

Provide support to the NixOS operating system.

### Describe alternatives you've considered

Are there some workaround to run SI in NixOS environment?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by keeb** [comment]
Thank for you for the feature-request! We will take this under advisement.

**Comment by nickgerace** [comment]
Tested with latest `main`, NixOS works following our development environment documentation.
