### ISSUE TITLE
Console errors `too much recursion` and `Vue internals bug` while editing asset

### ISSUE THREAD

**Issue by Octogonapus** [systeminit/si#3141]
### What happened?

I was working on a new asset and at one point the Update Asset button got stuck as the Success button and the code editor disappeared. After this point, navigating back to the model page broke (no page navigation happens, `TypeError: node is null` is printed to console). I saved the console log (attached).

![image](https://github.com/systeminit/si/assets/4064722/092434b1-e6a7-415d-a459-0d81eefc072a)

[console-export-2024-1-9_21-26-15.txt](https://github.com/systeminit/si/files/13882255/console-export-2024-1-9_21-26-15.txt)

### How can we reproduce this?

I'm not sure but you could try creating a new asset and making some edits, periodically clicking Update Asset. I also periodically switched tabs in the editor and used the format button. I enabled and disabled vim mode once.

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

A viable workaround is re-opening the workspace.

**Comment by stack72** [comment]
I don't see these now that we have rebuilt this feature
