### ISSUE TITLE
Asset is marked as in use until workspace is reloaded

### ISSUE THREAD

**Issue by Octogonapus** [systeminit/si#3142]
### What happened?

When editing as asset that is in use because it's in the model (but never actually created), that asset is marked as in use as expected. If you then delete the asset and go back to the customization tab, the asset is still marked as in use. Re-opening the workspace fixes this.

https://github.com/systeminit/si/assets/4064722/d5f7ae69-6847-4f49-a801-387f0d1aa837

### How can we reproduce this?

Follow the steps in the video

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stack72** [comment]
This is closed out in the new engine - we now allow updating an asset in place
