### ISSUE TITLE
si linux binary requires glibc 2.38+

### ISSUE THREAD

**Issue by rhass** [systeminit/si#3740]
### What happened?

I am unable to run the si binary on Ubuntu 22.04. 

```
./si: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./si)
```

### How can we reproduce this?

Attempt to run si on an Ubuntu 22.04 system with release: bin/si/binary/20240403.182853.0-sha.7886e405c

### Operating system

Linux

### Architecture

x86_64 / amd64

### What browsers are you seeing the problem on?

Other (please specify)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickgerace** [comment]
Hello! We no longer support the binary nor do we publish releases for it, as referenced in [this issue](https://github.com/systeminit/si/issues/2660#issuecomment-2089314484).

That being said, we are investigating more ways for folks to use the System Initiative software. For now, please refer to the instructions in the [README](https://github.com/systeminit/si/blob/main/README.md) for how to run the software locally. Thank you.
