### ISSUE TITLE
allow rebinding of shortcuts for moving around the graph (scroll/grab/etc)

### ISSUE THREAD

**Issue by NeilHanlon** [systeminit/si#3987]
### Is this issue related to an issue?.

When using the SI UI on a non-mac, the default binding of CMD+scroll for Zoom is problematic on other OSes which have that keycode bound (e.g., it's my "Meta" key for my window manager, so this keybind does zoom the graph, but also cycles through my active window layouts :) )

### Describe the outcome you'd like from us

Allow for rebinding of keyboard/mouse shortcuts

### Describe alternatives you've considered

Support for non-MacOS scrolling using e.g. Ctrl+Scroll would also solve my immediate pain

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by umag** [comment]
Bump that, I cant use spacebar for moving around as its binded for shift for me if I hold it
