### ISSUE TITLE
Running on localhost without the use of Docker

### ISSUE THREAD

**Issue by anjanesh** [systeminit/si#4747]
Is there a way to run `systeminit` locally (on Windows 11 using WSL2) without Docker ?

**Comment by stack72** [comment]
Hi @anjanesh 

Unfortunately there are no plans to remove any of the docker pieces from our local setup. We use it to run all of our supporting services (databases, metrics etc.) 

The alternative is to run a workspace in our SaaS which you can find when you sign into the service at https://auth.systeminit.com

Paul

**Comment by anjanesh** [comment]
I have not yet installed Docker on my work Windows 11 laptop of 16GB RAM where I have multiple IDEs and browsers open almost 24/7. My only concern is of Docker hogging too much of my resources. Can I run docker on my WSL on Windows 11 with port forwarding and then view it in the browser on Windows ?

**Comment by stack72** [comment]
Hi @anjanesh 

There are a large number of services to run System Initiative locally - that includes docker containers for the function executions as well as databases and Otel collectors. You will use a large chunk (if not all) of that 16GB memory to run it

Your best bet may be to try and use a service hosted workspace or try a dev VM running in the cloud with a lot of memory

Paul
